---
- name: Trigger job from stream
  hosts: all
  execution_strategy: parallel
  sources:
    - ansible.eda.event_stream: {}

  rules:
    - name: "Launch dynamic workflow"
      condition: event.payload.template_id is defined
      action:
        run_workflow_template:
          name: "{{ event.payload.template_id }}"
          organization: "Default"
          wait: false
          job_args:
            limit: "{{ event.payload.target_host }}"
